#ifndef APP_CONFIG_H_INCLUDED
#define APP_CONFIG_H_INCLUDED


#define APP_CONFIG_FIRMWARE_VERSION_MAJOR 0
#define APP_CONFIG_FIRMWARE_VERSION_MINOR 1
#define APP_CONFIG_FIRMWARE_VERSION_PATCH 0

#define APP_CONFIG_DATA_PATH "./data"


#endif